### ISSUE TITLE
ERROR CONECTION WITH API

### ISSUE THREAD

**Issue by Pablohe18** [creativetimofficial/ct-vue-argon-dashboard-pro-laravel#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes] I am running the latest version
- [yes] I checked the documentation and found no answer
- [yes] I checked to make sure that this issue has not already been filed
- [yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Front end connection with back end

# Current behavior

What is the current behavior?

The page has no connection to the backend

# Fault information (for errors)

The problem is that I don't know which port to put for my api in the project's .env
exactly in:

VUE_APP_BASE_URL = http: // localhost: 8081
VUE_APP_API_BASE_URL = ???

**Comment by teamupdivision** [comment]
Hello @Pablohe18 

Thanks for using Creative Tim products!

Can you please check the docs in the readme: https://github.com/creativetimofficial/ct-vue-argon-dashboard-pro-laravel
Read everything up until the Usage section.

Let us know if you still have issues.

Best

**Comment by teamupdivision** [comment]
Hi @Pablohe18,

Hope this solved the problem. Please let us know if there is anything else we can help with.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @Pablohe18 ,

Hope this solved the problem. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
