### ISSUE TITLE
Could not resolve dependency: peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/ct-vue-argon-dashboard-pro-laravel#2]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When setting up the application, `npm install` fails. 

1. Navigate to your Vue Argon Dashboard project folder: `cd your-vue-argon-dashbord-project`
2. Install project dependencies: `npm install`

# Current Behavior

Could not resolve dependency:
peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
node_modules/eslint-plugin-vue
eslint-plugin-vue@"^6.2.2" from the root project

# Failure Information (for bugs)
```➜ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vue-argon-dashboard-pro@1.1.0
npm ERR! Found: eslint@7.28.0
npm ERR! node_modules/eslint
npm ERR!   eslint@"^7.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   eslint-plugin-vue@"^6.2.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/japrehm/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/japrehm/.npm/_logs/2021-06-11T14_13_55_735Z-debug.log
```

## Steps to Reproduce

1. Navigate to your Vue Argon Dashboard project folder: `cd your-vue-argon-dashbord-project`
2. Install project dependencies: `npm install`

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: M1 Mac
* Operating System: Mac OS Big Sur
* Browser and Version: Chrome 91.0.4472.77 (Official Build) (arm64)
* Node Version: v15.10.0
* NPM Version: 7.17.0

## Failure Logs

```
0 verbose cli [
0 verbose cli   '/Users/japrehm/.nvm/versions/node/v15.10.0/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@7.17.0
2 info using node@v15.10.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/japrehm/code/vue-argon-dashboard-pro/.npmrc Completed in 2ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/Users/japrehm/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 timing npm:load:configload Completed in 12ms
20 timing npm:load:setTitle Completed in 4ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 21ms
26 timing config:load:flatten Completed in 3ms
27 timing arborist:ctor Completed in 1ms
28 timing arborist:ctor Completed in 0ms
29 timing idealTree:init Completed in 76ms
30 timing idealTree:userRequests Completed in 1ms
31 silly idealTree buildDeps
32 silly fetch manifest @fullcalendar/core@^4.4.2
33 http fetch GET 200 https://registry.npmjs.org/@fullcalendar%2fcore 212ms (cache revalidated)
34 silly fetch manifest @fullcalendar/daygrid@^4.4.2
35 http fetch GET 200 https://registry.npmjs.org/@fullcalendar%2fdaygrid 71ms (cache revalidated)
36 silly fetch manifest @fullcalendar/interaction@^4.4.2
37 http fetch GET 200 https://registry.npmjs.org/@fullcalendar%2finteraction 60ms (cache revalidated)
38 silly fetch manifest @fullcalendar/timegrid@^4.4.2
39 http fetch GET 200 https://registry.npmjs.org/@fullcalendar%2ftimegrid 196ms (cache revalidated)
40 silly fetch manifest @fullcalendar/vue@^4.4.2
41 http fetch GET 200 https://registry.npmjs.org/@fullcalendar%2fvue 665ms (cache revalidated)
42 silly fetch manifest vue@2.6.11
43 http fetch GET 200 https://registry.npmjs.org/vue 53ms (cache revalidated)
44 silly fetch manifest axios@^0.20.0
45 http fetch GET 200 https://registry.npmjs.org/axios 88ms (cache revalidated)
46 silly fetch manifest babel-eslint@^10.1.0
47 http fetch GET 200 https://registry.npmjs.org/babel-eslint 35ms (cache revalidated)
48 silly fetch manifest eslint@^7.1.0
49 http fetch GET 200 https://registry.npmjs.org/eslint 53ms (cache revalidated)
50 silly fetch manifest bootstrap@^4.5.0
51 http fetch GET 200 https://registry.npmjs.org/bootstrap 41ms (cache revalidated)
52 silly fetch manifest jquery@1.9.1 - 3
53 http fetch GET 200 https://registry.npmjs.org/jquery 51ms (cache revalidated)
54 silly fetch manifest popper.js@^1.16.1
55 http fetch GET 200 https://registry.npmjs.org/popper.js 57ms (cache revalidated)
56 silly fetch manifest chart.js@2.9.3
57 http fetch GET 200 https://registry.npmjs.org/chart.js 55ms (cache revalidated)
58 silly fetch manifest core-js@^3.6.5
59 http fetch GET 200 https://registry.npmjs.org/core-js 44ms (cache revalidated)
60 silly fetch manifest d3@^5.16.0
61 http fetch GET 200 https://registry.npmjs.org/d3 44ms (cache revalidated)
62 silly fetch manifest datamaps@0.5.9
63 http fetch GET 200 https://registry.npmjs.org/datamaps 52ms (cache revalidated)
64 silly fetch manifest date-fns@^2.14.0
65 http fetch GET 200 https://registry.npmjs.org/date-fns 60ms (cache revalidated)
66 silly fetch manifest dotenv@^8.2.0
67 http fetch GET 200 https://registry.npmjs.org/dotenv 57ms (cache revalidated)
68 silly fetch manifest dropzone@5.7.1
69 http fetch GET 200 https://registry.npmjs.org/dropzone 50ms (cache revalidated)
70 silly fetch manifest element-ui@2.13.2
71 http fetch GET 200 https://registry.npmjs.org/element-ui 52ms (cache revalidated)
72 silly fetch manifest es6-promise@^4.2.8
73 http fetch GET 200 https://registry.npmjs.org/es6-promise 108ms (cache revalidated)
74 silly fetch manifest eslint-plugin-vue@^6.2.2
75 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-vue 40ms (cache revalidated)
76 silly fetch manifest eslint@^5.0.0 || ^6.0.0
77 timing idealTree Completed in 2391ms
78 timing command:install Completed in 2411ms
79 verbose stack Error: unable to resolve dependency tree
79 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1210:25)
79 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1177:34)
79 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:880:11)
79 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
79 verbose stack     at async Promise.all (index 1)
79 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:136:5)
79 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:150:5)
80 verbose cwd /Users/japrehm/code/vue-argon-dashboard-pro
81 verbose Darwin 20.5.0
82 verbose argv "/Users/japrehm/.nvm/versions/node/v15.10.0/bin/node" "/usr/local/bin/npm" "install"
83 verbose node v15.10.0
84 verbose npm  v7.17.0
85 error code ERESOLVE
86 error ERESOLVE unable to resolve dependency tree
87 error
88 error While resolving: vue-argon-dashboard-pro@1.1.0
88 error Found: eslint@7.28.0
88 error node_modules/eslint
88 error   eslint@"^7.1.0" from the root project
88 error
88 error Could not resolve dependency:
88 error peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
88 error node_modules/eslint-plugin-vue
88 error   eslint-plugin-vue@"^6.2.2" from the root project
88 error
88 error Fix the upstream dependency conflict, or retry
88 error this command with --force, or --legacy-peer-deps
88 error to accept an incorrect (and potentially broken) dependency resolution.
88 error
88 error See /Users/japrehm/.npm/eresolve-report.txt for a full report.
89 verbose exit 1
```

**Comment by teamupdivision** [comment]
Hi @japrehm, 

Thanks for reporting the issue and for using Creative Tim products. 

Could you try updating the node version to 15.0.0 or more?  

Please let us know if this worked. 

All the best,
UPDIVISION Team

**Comment by ghost** [comment]
@teamupdivision 

I am using node v15.10.0 and npm 7.17.0.

**Comment by teamupdivision** [comment]
Hi @japrehm,

Thanks for the quick response and confirmation. It looks like there was confusion or a misunderstanding somewhere. It should work with less than 15.0.0. Sorry for the confusion. 

Please let us know if this is working well or if there are any other issues.

Best,
UPDIVISION Team

**Comment by ghost** [comment]
Ok, I downgraded to Node v14.17.1 and npm to 6.14.13. 

`npm install` now works now. Are there any plans to upgrade this to be compatible with newer versions of node/npm?

But when I do `npm run serve` I am getting this message 

```
 WARNING  Compiled with 1 warnings

 warning  in ./src/store/modules/auth.js

"export 'VueAuthenticate' was not found in 'vue-authenticate'
```

I can fix the error by updating the `auth.js` file line 3 to `import VueAuthenticate from "vue-authenticate";` But then the login button on the home screen does not work.

**Comment by teamupdivision** [comment]
Hi @japrehm,

Thank you very much for the additional details. We're investigating this issue and we'll get back shortly. 

Also, we're considering this upgrade, thanks.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @japrehm,
 
We've pushed a fix to this problem.
You can access it by downloading the product from the downloads section in the Creative Tim website.

Please make sure you install project dependencies (npm install) after downloading the updates.

Let us know if all works well now and there is anything else we can help with. 

All the best,
UPDIVISION Team

**Comment by cjholowatyj** [comment]
I'm having a similar issue, but when I go to the downloads page it still downloads the same zip files... I purchased the laravel bundle and not the individual template, so I'm hoping that is the snafoo there... any chance the bundle links can also be updated?

**Comment by teamupdivision** [comment]
Hi @cjholowatyj,

Thanks for your message and for reporting this issue. Can you please share with us the json file you downloaded here? It will help a lot in investigating this further.

Thank you,
UPDIVISION Team

**Comment by ghost** [comment]
I'm still seeing that it is version 1.0.0 as well, but it looks like this might just be an issue with the website versioning? The only change in the package.json file is the vue-authenticate verison? From `"vue-authenticate": "^1.4.1",` to `"vue-authenticate": "1.4.1"`. 

I was able to get vue-authenticate working with the old version by changing the auth.js file line 9 from `const vueAuth = new VueAuthenticate(Vue.prototype.$http, {` to `const vueAuth = VueAuthenticate.factory(Vue.prototype.$http, {` which will allow us to keep the package updated.

**Comment by cjholowatyj** [comment]
So the package.json version I'm using is showing v1.1.0 which I can see was updated June 29th, 2021 (though again, in the bundle I purchased it displays on the webpage as 1.0.0) I have zipped and attached as requested.
[package.json.zip](https://github.com/creativetimofficial/ct-vue-argon-dashboard-pro-laravel/files/6762075/package.json.zip)


I'm currently getting the following error output when attempting to run `npm update` to refresh the dependencies (lockfile warnings excluded):
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vue-argon-dashboard-pro@1.1.0
npm ERR! Found: eslint@7.30.0
npm ERR! node_modules/eslint
npm ERR!   eslint@"^7.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   eslint-plugin-vue@"^6.2.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/cjholowatyj/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cjholowatyj/.npm/_logs/2021-07-05T05_40_54_948Z-debug.log
```

If I run `npm update --legacy-peer-deps` it completes successfully (though warns of 24 vulnerabilities) but I still cannot see the dashboard on the front-end

**Comment by teamupdivision** [comment]
Hi @cjholowatyj,

Thanks for checking. Just to be sure, what is the node version you are using. Is it less than 15.0.0.? Please let us know. 

@japrehm Just checking if the issue was solved or if there is anything else we can do. 

Please let us know. 

Best,
Updivision Team

**Comment by cjholowatyj** [comment]
My bad @teamupdivision I was using node v16.4.0. It has to be under v15, right?

**Comment by teamupdivision** [comment]
Hi @cjholowatyj,

Thanks for the confirmation. Yes, this is correct. In case there is anything else we can help with, please let us know. 

Best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi there @japrehm @cjholowatyj,

We would like to check if the issues were solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by teamupdivision** [comment]
Hi @cjholowatyj @japrehm,
 
Hope this solved the problem. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Comment by parhamsagharchi** [comment]
Hi guys,

You can use [nvm](https://github.com/nvm-sh/nvm) for different versions of node, like this:

```
nvm list
nvm use xxx
```

And, Another point to keep my mind is that:

1. If you have **node_modules** folder and **package-lock.json** file in your root directory then remove those:

```
rm -r node_modules
rm package-lock.json
```

2. Then run commands:

```
npm cache clean --force
npm install --save --legacy-peer-deps
npm audit fix --force
```

3. Create a **.env** file in the root directory and paste the below code:

```
SKIP_PREFLIGHT_CHECK=true
```

Now, start your project.

Yours faithfully,
Parham

**Comment by kuishou68** [comment]
亲测有效，cnpm install 就好了！
