### ISSUE TITLE
Error when connecting backend with Vue

### ISSUE THREAD

**Issue by arnel-gomez** [creativetimofficial/ct-vue-argon-dashboard-pro-laravel#3]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ✓ ] I am running the latest version
- [ ✓ ] I checked the documentation and found no answer
- [ ✓ ] I checked to make sure that this issue has not already been filed
- [ ✓ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Trying to make connection with Laravel backend from Vue

# Current Behavior

Getting an error
Access to XMLHttpRequest at 'api' from origin 'http://localhost:8081' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by teamupdivision** [comment]
Hello, 

Thank you for using Creative TIM products. 

We apologies for the big delay in our response. 

Has the issue been resolved or is there something we can help you with? 

Thank you.
